package pokedex;

public class Pokemon 
{
    static String pokemon [][] =
{
  {"Bulbasaur", "Seed Pokemon", "Grass", "Poison","2'04\"", "15.2 lbs","A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokémon."  },
  {"Ivysaur", "Seed Pokemon", "Grass", "Poison","3'03\"", "28.7 lbs","When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs."  },
  {"Venusaur", "Seed Pokemon", "Grass", "Poison","6'07\"", "220.5 lbs","The plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight."  },
  {"Charmander", "Lizard Pokemon", "Fire", "None","2'00\"", "2'00 lbs","Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail."  },
  {"Charmeleon", "Flame Pokemon", "Fire", "None","3′7\"", "41.9 lbs","When it swings its burning tail, it elevates the temperature to unbearably high levels."  },
  {"Charizard", "Flame Pokemon", "Fire", "Flying","5'7\"", "199.5 lbs","Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally."  },
  {"Squirtle", "Tiny Turtle Pokemon", "Water", "None","1'8\"", "19.8 lbs","After birth, its back swells and hardens into a shell. Powerfully sprays foam from its mouth."  },
  {"Wartortle", "Turtle Pokemon", "Water", "None","3'3\"", "49.6 lbs","Often hides in water to stalk unwary prey. For swimming fast, it moves its ears to maintain balance."  },
  {"Blastoise", "Shellfish Pokemon", "Water", "None","5'3\"", "188.5 lbs","A brutal POKéMON with pressurized water jets on its shell. They are used for high speed tackles."  },
  {"Caterpie", "Worm Pokemon", "Bug", "None","1'0\"", "6.4 lbs","Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls."  },
  {"Metapod", "Cocoon Pokemon", "Bug", "None","2'4\"", "21.8 lbs","This POKéMON is vulnerable to attack while its shell is soft, exposing its weak and tender body."  },
  {"Butterfree", "Butterfly Pokemon", "Bug", "Flying","3'7\"", "70.5 lbs","In battle, it flaps its wings at high speed to release highly toxic dust into the air."  },
  {"Weedle", "Hairy Bug Pokemon", "Bug", "Poison","1'0\"", "7.1 lbs","Almost incapable of moving, this POKéMON can only harden its shell to protect itself from predators."  },
  {"Kakuna", "Cocoon Pokemon", "Bug", "Poison","2'00\"", "22 lbs","Almost incapable of moving, this POKéMON can only harden its shell to protect itself from predators."  },
  {"Beedrill", "Poison Bee Pokemon", "Bug", "Poison","3'03\"", "65 lbs","Flies at high speed and attacks using its large venomous stingers on its forelegs and tail."  },
  {"Pidgey", "Tiny Bird Pokemon", "Normal", "Flying","1'00\"", "4 lbs","A common sight in forests and woods. It flaps its wings at ground level to kick up blinding sand."  },
  {"Pidgeotto", "Bird Pokemon", "Normal", "Flying","3'07\"", "66.1 lbs","Very protective of its sprawling territorial area, this POKéMON will fiercely peck at any intruder."  },
  {"Pidgeot", "Bird Pokemon", "Normal", "Flying","4'11\"", "87.1 lbs","When hunting, it skims the surface of water at high speed to pick off unwary prey such as MAGIKARP."  },
  {"Ratatta", "Mouse Pokemon", "Normal", "None","1'00\"", "7.7 lbs","Bites anything when it attacks. Small and very quick, it is a common sight in many places."  },
  {"Raticate", "Mouse Pokemon", "Normal", "None","2'04\"", "40.8 lbs","It uses its whiskers to maintain its balance. It apparently slows down if they are cut off."  },
  {"Spearow", "Tiny Bird Pokemon", "Normal", "Flying","1'00\"", "4.4 lbs","Eats bugs in grassy areas. It has to flap its short wings at high speed to stay airborne."  },
  {"Fearow", "Beak Pokemon", "Normal", "Flying","3'11\"", "83.8 lbs","With its huge and magnificent wings, it can keep aloft without ever having to land for rest."  },
  {"Ekans", "Snake Pokemon", "Poison", "None","6'07\"", "15.2 lbs","Moves silently and stealthily. Eats the eggs of birds, such as Pidgey and Spearow, whole."  },
  {"Arbok", "Cobra Pokemon", "Poison", "None","11'06\"", "143.3 lbs","It is rumored that the ferocious warning markings on its belly differ from area to area."  },
  {"Pikachu", "Mouse Pokemon", "Electric", "None","1'04\"", "13.2 lbs","When several of these POKéMON gather, their electricity could build and cause lightning storms."  },
  {"Raichu", "Mouse Pokemon", "Electric", "None","2'07\"", "66.1 lbs","Its long tail serves as a ground to protect itself from its own high voltage power."  },
  {"Sandshrew", "Mouse Pokemon", "Ground", "None","2'00\"", "26.5 lbs","Burrows deep underground in arid locations far from water. It only emerges to hunt for food."  },
  {"Sandslash", "Mouse Pokemon", "Ground", "None","3'03\"", "65 lbs","Curls up into a spiny ball when threatened. It can roll while curled up to attack or escape."  },
  {"Nidoran♀", "Poison Pin Pokemon", "Poison", "None","1'04\"", "15.4 lbs","Although small, its venomous barbs render this POKéMON dangerous. The female has smaller horns."  },
  {"Nidorino", "Poison Pin Pokemon", "Poison", "None","2'07\"", "44.1 lbs","The female's horn develops slowly. Prefers physical attacks such as clawing and biting."  },
  {"Nidoqueen", "Drill Pokemon", "Poison", "Ground","4'03\"", "132.3 lbs","Its hard scales provide strong protection. It uses its hefty bulk to execute powerful moves."  },
  {"Nidoran♂", "Poison Pin Pokemon", "Poison", "None","1'08\"", "19.8 lbs","Stiffens its ears to sense danger. The larger its horns, the more powerful its secreted venom."  },
  {"Nidorino", "Poison Pin Pokemon", "Poison", "None","2'11\"", "43 lbs","An aggressive POKéMON that is quick to attack. The horn on its head secretes a powerful venom."  },
  {"Nidoking", "Drill Pokemon", "Poison", "Ground","4'07\"", "136.7 lbs","It uses its powerful tail in battle to smash, constrict, then break the prey's bones."  },
  {"Clefairy", "Fairy Pokemon", "Normal", "None","2'00\"", "16.5 lbs","Its magical and cute appeal has many admirers. It is rare and found only in certain areas."  },
  {"Clefable", "Fairy Pokemon", "Normal", "None","4'03\"", "88.2 lbs","A timid fairy POKéMON that is rarely seen. It will run and hide the moment it senses people."  },
  {"Vulpix", "Fox Pokemon", "Fire", "None","2'00\"", "21.8 lbs","At the time of birth, it has just one tail. The tail splits from its tip as it grows older."  },
  {"Ninetales", "Fox Pokemon", "Fire", "None","3'07\"", "43.9 lbs","Very smart and very vengeful. Grabbing one of its many tails could result in a 1000-year curse."  },
  {"Jigglypuff", "Balloon Pokemon", "Normal", "None","1'08\"", "12.1 lbs","When its huge eyes light up, it sings a mysteriously soothing melody that lulls its enemies to sleep."  },
  {"Wigglytuff", "Balloon Pokemon", "Normal", "None","3'03\"", "26.5 lbs","The body is soft and rubbery. When angered, it will suck in air and inflate itself to an enormous size."  },
  {"Zubat", "Bat Pokemon", "Poison", "Flying","2'07\"", "16.5 lbs","Forms colonies in perpetually dark places. Uses ultrasonic waves to identify and approach targets."  },
  {"Golbat", "Bat Pokemon", "Poison", "Flying","5'03\"", "121.3 lbs","Once it strikes, it will not stop draining energy from the victim even if it gets too heavy to fly."  },
  {"Oddish", "Weed Pokemon", "Grass", "Poison","1'08\"", "11.9 lbs","During the day, it keeps its face buried in the ground. At night, it wanders around sowing its seeds."  },
  {"Gloom", "Weed Pokemon", "Grass", "Poison","2'07\"", "19 lbs","The fluid that oozes from its mouth isn't drool. It is a nectar that is used to attract prey."  },
  {"Vileplume", "Flower Pokemon", "Grass", "Poison","3'11\"", "41 lbs","The larger its petals, the more toxic pollen it contains. Its big head is heavy and hard to hold up."  },
  {"Paras", "Mushroom Pokemon", "Bug", "Grass","1'00\"", "11.9 lbs","Burrows to suck tree roots. The mushrooms on its back grow by drawing nutrients from the bug host."  },
  {"Parasect", "Mushroom Pokemon", "Bug", "Grass","3'03\"", "65 lbs","A host-parasite pair in which the parasite mushroom has taken over the host bug. Prefers damp places."  },
  {"Venonat", "Insect Pokemon", "Poison", "Bug","3'03\"", "66.1 lbs","Lives in the shadows of tall trees where it eats insects. It is attracted by light at night."  },
  {"Venomoth", "Poison Moth Pokemon", "Poison", "Bug","4'11\"", "27.6 lbs","The dust-like scales covering its wings are color coded to indicate the kinds of poison it has."  },
  {"Diglett", "Mole Pokemon", "Ground", "None","0'08\"", "1.8 lbs","Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground."  },
  {"Dugtrio", "Mole Pokemon", "Ground", "None","2'04\"", "73.4 lbs","A team of DIGLETT triplets. It triggers huge earthquakes by burrowing 60 miles underground."  },
  {"Meowth", "Scratch Cat Pokemon", "Normal", "None","1'04\"", "9.3 lbs","Adores circular objects. Wanders the streets on a nightly basis to look for dropped loose change."  },
  {"Persian", "Classy Cat Pokemon", "Normal", "None","3'03\"", "70.5 lbs","Although its fur has many admirers, it is tough to raise as a pet because of its fickle meanness."  },
  {"Psyduck", "Duck Pokemon", "Water", "None","2'07\"", "43.2 lbs","While lulling its enemies with its vacant look, this wily POKéMON will use psychokinetic powers."  },
  {"Golduck", "Duck Pokemon", "Water", "None","5'07\"", "168.9 lbs","Often seen swimming elegantly by lake shores. It is often mistaken for the Japanese monster, Kappa."  },
  {"Mankey", "Pig Monkey Pokemon", "Fighting", "None","1'08\"", "61.7 lbs","Extremely quick to anger. It could be docile one moment then thrashing away the next instant."  },
  {"Primeape", "Pig Monkey Pokemon", "Fighting", "None","3'03\"", "70.5 lbs","Always furious and tenacious to boot. It will not abandon chasing its quarry until it is caught."  },
  {"Growlithe", "Puppy Pokemon", "Fire", "None","2'07\"", "41.9 lbs","Very protective of its territory. It will bark and bite to repel intruders from its space."  },
  {"Arcanine", "Legendary Pokemon", "Fire", "None","6'03\"", "341.7 lbs","A POKéMON that has been admired since the past for its beauty. It runs agilely as if on wings."  },
  {"Poliwag", "Tadpole Pokemon", "Water", "None","2'00\"", "27.3 lbs","Its newly grown legs prevent it from running. It appears to prefer swimming than trying to stand."  },
  {"Poliwhirl", "Tadpole Pokemon", "Water", "None","3'03\"", "44.1 lbs","Capable of living in or out of water. When out of water, it sweats to keep its body slimy."  },
  {"Poliwrath", "Tadpole Pokemon", "Water", "Fighting","4'03\"", "119  lbs","An adept swimmer at both the front crawl and breast stroke. Easily overtakes the best human swimmers."  },
  {"Abra", "Psy Pokemon", "Psychic", "None","2'11\"", "43 lbs","Using its ability to read minds, it will identify impending danger and TELEPORT to safety."  },
  {"Kadabra", "Psy Pokemon", "Psychic", "None","4'03\"", "124.6 lbs","It emits special alpha waves from its body that induce headaches just by being close by."  },
  {"Alakazam", "Psy Pokemon", "Psychic", "None","4'11\"", "105.8 lbs","Its brain can outperform a supercomputer. Its intelligence quotient is said to be 5,000."  },
  {"Machop", "Superpower Pokemon", "Fighting", "None","2'07\"", "43 lbs","Loves to build its muscles. It trains in all styles of martial arts to become even stronger."  },
  {"Machoke", "Superpower Pokemon", "Fighting", "None","4'11\"", "155.4 lbs","Its muscular body is so powerful, it must wear a power save belt to be able to regulate its motions."  },
  {"Machamp", "Superpower Pokemon", "Fighting", "None","5'03\"", "286.6 lbs","Using its heavy muscles, it throws powerful punches that can send the victim clear over the horizon."  },
  {"Bellsprout", "Flower Pokemon", "Grass", "Poison","2'04\"", "8.8 lbs","A carnivorous POKéMON that traps and eats bugs. It uses its root feet to soak up needed moisture."  },
  {"Weepinbell", "Flycatcher Pokemon", "Grass", "Poison","3'03\"", "14.1 lbs","It spits out POISONPOWDER to immobilize the enemy and then finishes it with a spray of ACID."  },
  {"Victreebel", "Flycatcher Pokemon", "Grass", "Poison","5'07\"", "34.2 lbs","	Said to live in huge colonies deep in jungles, although no one has ever returned from there."  },
  {"Tentacool", "Jellyfish Pokemon", "Water", "Poison","4'11\"", "100.3 lbs","Drifts in shallow seas. Anglers who hook them by accident are often punished by its stinging acid."  },
  {"Tentacruel", "Jellyfish Pokemon", "Water", "Poison","5'03\"", "121.3 lbs","The tentacles are normally kept short. On hunts, they are extended to ensnare and immobilize prey."  },
  {"Geodude", "Rock Pokemon", "Rock", "Ground","2'00\"", "44.1 lbs","Found in fields and mountains. Mistaking them for boulders, people often step or trip on them."  },
  {"Graveler", "Rock Pokemon", "Rock", "Ground","3'03\"", "231.5 lbs","Rolls down slopes to move. It rolls over any obstacle without slowing or changing its direction."  },
  {"Golem", "Megaton Pokemon", "Rock", "Ground","4'07\"", "661.4 lbs","Its boulder-like body is extremely hard. It can easily withstand dynamite blasts without damage."  },
  {"Ponyta", "Fire Horse Pokemon", "Fire", "None","3'03\"", "66.1 lbs","Its hooves are 10 times harder than diamonds. It can trample anything completely flat in little time."  },
  {"Rapidash", "Fire Horse Pokemon", "Fire", "None","5'07\"", "209.4 lbs","Very competitive, this POKéMON will chase anything that moves fast in the hopes of racing it."  },
  {"Slowpoke", "Dopey Pokemon", "Psychic", "Water","3'11\"", "79.4 lbs","Incredibly slow and dopey. It takes 5 seconds for it to feel pain when under attack."  },
  {"Slowbro", "Hermit Crab Pokemon", "Psychic", "Water","5'03\"", "173.1 lbs","The SHELLDER that is latched onto SLOWPOKE's tail is said to feed on the host's left over scraps."  },
  {"Magnemite", "Magnet Pokemon", "Electric", "None","1'00\"", "13.2 lbs","Uses anti-gravity to stay suspended. Appears without warning and uses THUNDER WAVE and similar moves."  },
  {"Magneton", "Magnet Pokemon", "Electric", "None","3'03\"", "132.3  lbs","Formed by several MAGNEMITEs linked together. They frequently appear when sunspots flare up."  },
  {"Farfetch'd", "Wild Duck Pokemon", "Normal", "Flying","2'07\"", "33.1 lbs","The sprig of green onions it holds is its weapon. It is used much like a metal sword."  },
  {"Doduo", "Twin Bird Pokemon", "Normal", "Flying","4'07\"", "86.4 lbs","A bird that makes up for its poor flying with its fast foot speed. Leaves giant footprints."  },
  {"Dodrio", "Triple Bird Pokemon", "Normal", "Flying","5'11\"", "187.8  lbs","Uses its three brains to execute complex plans. While two heads sleep, one head stays awake."  },
  {"Seel", "Sea Lion Pokemon", "Water", "None","3'07\"", "198.4 lbs","The protruding horn on its head is very hard. It is used for bashing through thick ice."  },
  {"Dewgong", "Sea Lion Pokemon", "Water", "Ice","5'07\"", "264.6 lbs","Stores thermal energy in its body. Swims at a steady 8 knots even in intensely cold waters."  },
  {"Grimer", "Sludge Pokemon", "Poison", "None","2'11\"", "66.1 lbs","Appears in filthy areas. Thrives by sucking up polluted sludge that is pumped out of factories."  },
  {"Muk", "Sludge Pokemon", "Poison", "None","3'11\"", "66.1 lbs","Thickly covered with a filthy, vile sludge. It is so toxic, even its footprints contain poison."  },
  {"Shelder", "Bivalve Pokemon", "Water", "None","1'00\"", "8.8 lbs","Its hard shell repels any kind of attack. It is vulnerable only when its shell is open."  },
  {"Cloyster", "Bivalve Pokemon", "Water", "Ice","4'11\"", "292.1 lbs","When attacked, it launches its horns in quick volleys. Its innards have never been seen."  },
  {"Gastly", "Gas Pokemon", "Ghost", "Poison","4'03\"", "0.2 lbs","Almost invisible, this gaseous POKéMON cloaks the target and puts it to sleep without notice."  },
  {"Haunter", "Gas Pokemon", "Ghost", "Poison","5'03\"", "0.2 lbs","Because of its ability to slip through block walls, it is said to be from another dimension."  },
  {"Gengar", "Shadow Pokemon", "Ghost", "Poison","4'11\"", "89.3 lbs","Under a full moon, this POKéMON likes to mimic the shadows of people and laugh at their fright."  },
  {"Onix", "Rock Snake Pokemon", "Rock", "Ground","28'10\"", "463 lbs","As it grows, the stone portions of its body harden to become similar to a diamond, but colored black."  },
  {"Drowzee", "Hypnosis Pokemon", "Psychic", "None","3'03\"", "71.4 lbs","Puts enemies to sleep then eats their dreams. Occasionally gets sick from eating bad dreams."  },
  {"Hypno", "Hypnosis Pokemon", "Psychic", "None","5'03\"", "166.7 lbs","When it locks eyes with an enemy, it will use a mix of PSI moves such as HYPNOSIS and CONFUSION."  },
  {"Krabby", "River Crab Pokemon", "Water", "None","1'04\"", "14.3 lbs","Its pincers are not only powerful weapons, they are used for balance when walking sideways."  },
  {"Kingler", "Pincer Pokemon", "Water", "None","4'03\"", "132.3 lbs","The large pincer has 10000 hp of crushing power. However, its huge size makes it unwieldy to use."  },
  {"Voltorb", "Ball Pokemon", "Electric", "None","1'08\"", "22.9 lbs","Usually found in power plants. Easily mistaken for a POKé BALL, they have zapped many people."  },
  {"Electrode", "Ball Pokemon", "Electric", "None","3'11\"", "146.8 lbs","It stores electric energy under very high pressure. It often explodes with little or no provocation."  },
  {"Exeggcute", "Egg Pokemon", "Psychic", "Grass","1'04\"", "5.5 lbs","	Often mistaken for eggs. When disturbed, they quickly gather and attack in swarms."  },
  {"Exeggcutor", "Coconut Pokemon", "Psychic", "Grass","6'07\"", "264.6 lbs","Legend has it that on rare occasions, one of its heads will drop off and continue on as an EXEGGCUTE."  },
  {"Cubone", "Lonely Pokemon", "Ground", "None","1'04\"", "14.3 lbs","Because it never removes its skull helmet, no one has ever seen this POKéMON's real face."  },
  {"Marowak", "Bone Keeper Pokemon", "Ground", "None","3'03\"", "99.2 lbs","The bone it holds is its key weapon. It throws the bone skillfully like a boomerang to KO targets."  },
  {"Hitmonlee", "Kicking Pokemon", "Fighting", "None","4'11\"", "109.8 lbs","When in a hurry, its legs lengthen progressively. It runs smoothly with extra long, loping strides."  },
  {"Hitmonchan", "Punching Pokemon", "Fighting", "None","4'07\"", "110.7 lbs","While apparently doing nothing, it fires punches in lightning fast volleys that are impossible to see."  },
  {"Lickitung", "Licking Pokemon", "Normal", "None","3'11\"", "144.4 lbs","Its tongue can be extended like a chameleon's. It leaves a tingling sensation when it licks enemies."  },
  {"Koffing", "Poison Gas Pokemon", "Poison", "None","2'00\"", "2.2 lbs","Because it stores several kinds of toxic gases in its body, it is prone to exploding without warning."  },
  {"Weezing", "Poison Gas Pokemon", "Poison", "None","3'11\"", "20.9 lbs","Where two kinds of poison gases meet, 2 KOFFINGs can fuse into a WEEZING over many years."  },
  {"Rhyhorn", "Spikes Pokemon", "Rock", "Ground","3'03\"", "253.5 lbs","Its massive bones are 1000 times harder than human bones. It can easily knock a trailer flying."  },
  {"Rhydon", "Drill Pokemon", "Rock", "Ground","6'03\"", "264.6 lbs","Protected by an armor-like hide, it is capable of living in molten lava of 3,600 degrees."  },
  {"Chansey", "Egg Pokemon", "Normal", "None","3'07\"", "76.3 lbs","A rare and elusive POKéMON that is said to bring happiness to those who manage to get it."  },
  {"Tangela", "Vine Pokemon", "Grass", "None","3'03\"", "77.2 lbs","The whole body is swathed with wide vines that are similar to seaweed. Its vines shake as it walks."  },
  {"Kangaskhan", "Parent Pokemon", "Normal", "None","7'03\"", "176.4 lbs","The infant rarely ventures out of its mother's protective pouch until it is 3 years old."  },
  {"Horsea", "Dragon Pokemon", "Water", "None","1'04\"", "17.6 lbs","Known to shoot down flying bugs with precision blasts of ink from the surface of the water."  },
  {"Seadra", "Dragon Pokemon", "Water", "None","3'11\"", "55.1 lbs","Capable of swimming backwards by rapidly flapping its wing-like pectoral fins and stout tail."  },
  {"Goldeen", "Goldfish Pokemon", "Water", "None","2'00\"", "33.1 lbs","Its tail fin billows like an elegant ballroom dress, giving it the nickname of the Water Queen."  },
  {"Seaking", "Goldfish Pokemon", "Water", "None","4'03\"", "86 lbs","In the autumn spawning season, they can be seen swimming powerfully up rivers and creeks."  },
  {"Staryu", "Star Shape Pokemon", "Water", "None","2'07\"", "76.1 lbs","An enigmatic POKéMON that can effortlessly regenerate any appendage it loses in battle."  },
  {"Starmie", "Mysterious Pokemon", "Water", "Psychic","3'07\"", "176.4 lbs","Its central core glows with the seven colors of the rainbow. Some people value the core as a gem."  },
  {"Mr. Mime", "Barrier Pokemon", "Psychic", "None","4'03\"", "120.2 lbs","If interrupted while it is miming, it will slap around the offender with its broad hands."  },
  {"Scyther", "Mantis Pokemon", "Bug", "Flying","4'11\"", "123.5 lbs","With ninja-like agility and speed, it can create the illusion that there is more than one."  },
  {"Jynx", "Human Shape Pokemon", "Psychic", "Ice","4'07\"", "89.5 lbs","It seductively wiggles its hips as it walks. It can cause people to dance in unison with it."  },
  {"Electabuzz", "Electric Pokemon", "Electric", "None","3'07\"", "66.1 lbs","Normally found near power plants, they can wander away and cause major blackouts in cities."  },
  {"Magmar", "Spitfire Pokemon", "Fire", "None","4'03\"", "98.1 lbs","Its body always burns with an orange glow that enables it to hide perfectly among flames."  },
  {"Pinsir", "Stag Beetle Pokemon", "Bug", "None","4'11\"", "121.3 lbs","If it fails to crush the victim in its pincers, it will swing it around and toss it hard."  },
  {"Tauros", "Wild Bull Pokemon", "Normal", "None","4'07\"", "194.9 lbs","When it targets an enemy, it charges furiously while whipping its body with its long tails."  },
  {"Magikarp", "Fish Pokemon", "Water", "None","2'11\"", "22 lbs","In the distant past, it was somewhat stronger than the horribly weak descendants that exist today."  },
  {"Gyarados", "Atrocious Pokemon", "Water", "Flying","21'4\"", "518.1 lbs","Rarely seen in the wild. Huge and vicious, it is capable of destroying entire cities in a rage."  },
  {"Lapras", "Transport Pokemon", "Water", "Ice","8'02\"", "485 lbs","A POKéMON that has been overhunted almost to extinction. It can ferry people across the water."  },
  {"Ditto", "Transform Pokemon", "Normal", "None","1'00\"", "8.8 lbs","Capable of copying an enemy's genetic code to instantly transform itself into a duplicate of the enemy."  },
  {"Eevee", "Evolution Pokemon", "Normal", "None","1'00\"", "14.3 lbs","Its genetic code is irregular. It may mutate if it is exposed to radiation from element STONEs."  },
  {"Vaporeon", "Bubble Jet Pokemon", "Water", "None","3'03\"", "63.9 lbs","Lives close to water. Its long tail is ridged with a fin which is often mistaken for a mermaid's."  },
  {"Jolteon", "Lightning Pokemon", "Electric", "None","2'07\"", "54 lbs","It accumulates negative ions in the atmosphere to blast out 10000-volt lightning bolts."  },
  {"Flareon", "Flame Pokemon", "Fire", "None","2'11\"", "55.1 lbs","When storing thermal energy in its body, its temperature could soar to over 1600 degrees."  },
  {"Porygon", "Virtual Pokemon", "Normal", "None","2'07\"", "80.5 lbs","A POKéMON that consists entirely of programming code. Capable of moving freely in cyberspace."  },
  {"Omanyte", "Spiral Pokemon", "Rock", "Water","1'04\"", "16.5 lbs","Although long extinct, in rare cases, it can be genetically resurrected from fossils."  },
  {"Omastar", "Spiral Pokemon", "Rock", "Water","3'03\"", "77.2 lbs","A prehistoric POKéMON that died out when its heavy shell made it impossible to catch prey."  },
  {"Kabuto", "Shellfish Pokemon", "Rock", "Water","1'08\"", "25.4 lbs","A POKéMON that was resurrected from a fossil found in what was once the ocean floor eons ago."  },
  {"Kabutops", "Shellfish Pokemon", "Rock", "Water","4'03\"", "89.3 lbs","Its sleek shape is perfect for swimming. It slashes prey with its claws and drains the body fluids."  },
  {"Aerodactyl", "Fossil Pokemon", "Rock", "Flying","5'11\"", "130.1 lbs","A ferocious, prehistoric POKéMON that goes for the enemy's throat with its serrated saw-like fangs."  },
  {"Snorlax", "Sleeping Pokemon", "Normal", "None","6'11\"", "1014.1 lbs","Very lazy. Just eats and sleeps. As its rotund bulk builds, it becomes steadily more slothful."  },
  {"Articuno", "Freeze Pokemon", "Ice", "Flying","5'07\"", "122.1 lbs","A legendary bird POKéMON that is said to appear to doomed people who are lost in icy mountains."  },
  {"Zapdos", "Electric Pokemon", "Electric", "Flying","5'03\"", "116 lbs","A legendary bird POKéMON that is said to appear from clouds while dropping enormous lightning bolts."  },
  {"Moltres", "Flame Pokemon", "Fire", "Flying","6'07\"", "132.3 lbs","Known as the legendary bird of fire. Every flap of its wings creates a dazzling flash of flames."  },
  {"Dratini", "Dragon Pokemon", "Dragon", "None","5'11\"", "7.3 lbs","Long considered a mythical POKéMON until recently when a small colony was found living underwater."  },
  {"Dragonair", "Dragon Pokemon", "Dragon", "None","13'01\"", "36.4 lbs","A mystical POKéMON that exudes a gentle aura. Has the ability to change climate conditions."  },
  {"Dragonite", "Dragon Pokemon", "Dragon", "Flying","7'03\"", "463 lbs","An extremely rarely seen marine POKéMON. Its intelligence is said to match that of humans."  },
  {"Mewtwo", "Genetic Pokemon", "Psychic", "None","6'07\"", "269 lbs","It was created by a scientist after years of horrific gene splicing and DNA engineering experiments."  },
  {"Mew", "New Species Pokemon", "Psychic", "None","1'04\"", "8.8 lbs","So rare that it is still said to be a mirage by many experts. Only a few people have seen it worldwide."  },
};

    public static String[][] getPokemon()
    {
       return Pokemon.pokemon; 
    }
}
